16.Django/my_polls/config/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView #뒤쪽에서 배움 그냥 그러려니 일단 하시오

urlpatterns = [
    #http://127.0.0.1:8000/ >> home.html을 직접 호출
    path("", TemplateView.as_view(template_name = 'home.html'), name = 'home'), #
    path('admin/', admin.site.urls),
    path('poll/', include("poll.urls")), #url path가 poll/
    
]

16.Django/my_polls/poll/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

#View 모듈 import
from . import views

#요청 url - 함수 매핑 >> urlpatterns 변수의 리스트에 등록
app_name = 'poll'
urlpatterns = [
    path("list", views.list, name='list'), #poll/list >> views.list 함수 호출
    path("vote_form/<int:question_id>", views.vote_form, name='vote_form'), #poll/vote_form >> view.vote_form ..?
    path("vote", views.vote, name='vote'),
    path("my_vote_result/<int:question_id>", views.vote_result, name = "vote_result"),
]


#사용자 요청 url - http://ip:port/resourcepath
#config.urls.py에 등록 : resource_path
#resource_path : app_root/나머지_path
#config/urls.py : app_root/(poll/)  >> poll/urls.py에서 나머지 _path를 확인
#poll/urls.py : 

16.Django/my_polls/poll/models.py
from django.db import models


'''
# Question(질문) 테이블과 연결된 모델 클래스
    -qustion_text = 질문 내용 - varchar
    -pub_date = 등록 일시 - datetime
    -id(PK - 자동생성되도록 할거임) - 1씩 자동적으로 증가하는 값
''' 

#모델 클래스
#    -models.Model를 상속
#    -컬럼 관련 변수들을 class변수로 정의 >> Field
#    -class이름 : 테이블명으로 이름 지정, Pascal표기법 사용
class Question(models.Model):
    #Field 클래스 변수 : 변수명-컬럼명, 값-field객체 >> 데이터 타입, 추가 설정
    #Primary key 컬럼 생략 >> 자동으로 id라는 이름의 자동증가 정수형 컬럼이 생성된다

    question_text = models.CharField(max_length=200) #charfiled : 문자열(varchar)
    pub_date = models.DateTimeField(auto_now_add=True) #Datetimefiled : 일시타입(date) - auto_now_add=True : 일시를 자동으로 등록

        #sql에서 다음과 비슷
        #create table Question(
        #   question_text varchar(200) not null primary
        # )

    def __str__(self):
        return self.question_text

#Choice - 보기
#   -choice_text : 보기 내용 - varchar
#   -vote : 몇번 선택 되었는지 - int(number)
#   -question : 질문에 대한 보기 - Quesion의 Foreign key 컬럼
#   -id : 자동증가 PK (따로 만들지 않겠다)
class Choice(models.Model):
    #field 정의
    choice_text = models.CharField(max_length=200)
    vote = models.PositiveIntegerField(default=0) #PositiveIntegerField:양수정수타입 / defalut:기본값 설정
    question = models.ForeignKey(to=Question, on_delete=models.CASCADE) #ForiegnKey : ForeignKey필드 선언 / to : 부모 테이블, on_delete : 참조 데이터 삭제시 설정(CASECADE : 부모가 지워질시 참조하는 자식 테이블도 삭제)
    
    def __str__(self):
        return self.choice_text
    

# 모델 클래스를 작성/변경
# python manage.py makemigrations : DB에 테이블을 어떻게 만들지 정의
# python manage.py migrate        : DB에 적용(테이블 생성, 변경) / model과 db를 연결(연동)하는 역할

16.Django/my_polls/poll/views.py
from django.shortcuts import render, redirect
# 모델 클래스 import
from .models import Question, Choice
from django.urls import reverse

#View : 사용자 요청을 처리하는 함수(work flow). 기능별로 작성.
    #View 함수
    #1. 사용자가 전송한 파라미터(요청 파라미터, path parameter) 조회
    #2. 사용자가 전송한 파라미터를 검증(validation) 
    #   - 필수 파라미터 전송 여부
    #   - 값에 대한 조건을 확인(타입, 범위, 글자수 등)
    #   - 검증 실패 >> error처리 후 페이지 이동
    #3. Business logic 처리 - 사용자가 요청한 작업을 처리  
    #4. 처리 결과를 응답처리
    #   - Template 호출(render()), 다른 View를 호출(redirect())
    

#설문 목록을 보여주는 View 함수
#   1. DB에서 설문 목록(Question)을 조회
#   2. question_text만 추출해서 List 생성
#   3. 응답화면을 생성해서 반환 >> Template 사용

# View함수 : 이름-알아서 정함 / 매개변수: 1-HttpRequest를 받는 변수
# View함수를 poll/urls.py에 등록 >> 사용자요청URL-View함수 매핑
def list(request):
    question_list = Question.objects.all()

    #응답
    response = render(request,
                      "poll/list.html", #응답을 처리할 template 파일. poll/templates/poll/list.html
                      {"question_list" : question_list}) #template에 전달할 name-value 쌍의 dict

    return response


#vote_form을 처리 View함수
#매개변수 : 1. HttpRequest, 2. question_id : Path Parameter로 전달된 질문 id를 변수
def vote_form(request, question_id):
    print("vote_form() : question_id", question_id)
    print('-------------------------------')
    #question_id로 QuestionChoice를 조회해서 template으로 전달
    try:
        question = Question.objects.get(pk = question_id)
        return render(request, 'poll/vote_form.html', {"question":question})

    except:
        #없는 question_id로 조회한 경우 >> 사용자가 없는 id설문을 요청
        return render(request, 'poll/error_page.html', {"error_message":"없는 설문번호를 요청하셨습니다!"})    



#투표 처리를 해주는 View함수
#요청 parameter를 조회 : choice = id, question_id = id
    # POST 방식 요청 처리 : request.POST['name'], request.POST.get('name')
    # GET 방식 요청 처리 : request.GET['name'], request.GET.get('name')
    # [] 조회 : 없는 name으로 조회할 경우 exception 발생
    # .get() : 없는 name으로 조회할 경우 default값 반환(default = None)
def vote(request):
    #요청 parameter를 조회 : choice = id, question_id = id
    #choice_id = request.POST['choice']
    choice_id = request.POST.get('choice')
    question_id = request.POST['question_id']

    #요청 파라미터 검증(validataion) - 필수 요청 파라미터가 잘 전송되었는지 체크
    if choice_id == None: #보기를 선택하지 않고 조회한 경우 >> vote_form.html을 호출
        question = Question.objects.get(pk=question_id)
        return render(request, 'poll/vote_form.html', {'question':question, "error_message":"보기를 선택하세요."})

    print("vote() : ", choice_id, question_id)
    #Choice를 update해주는 작업 필요 >> update choice set vote=vote+1 where id=선택된id
    #1.Choice조회 2.vote변경 3.save()
    choice = Choice.objects.get(pk=choice_id)
    choice.vote = choice.vote + 1
    choice.save()

    #Question을 select : select * from question where id=질문id
    #question = Question.objects.get(pk = question_id)
    
    #응답처리
    #return render(request, "poll/vote_result.html", {'question' : question})

    #url = f"/poll/vote_result/{question_id}"
    url = reverse("poll:vote_result", args=[question_id]) #("path name", args=[path 파라미터에 전달할 값, ...])
    print('--------------------redirect url: ', url)
    return redirect(to=url)


#질문 별 설문에 결과를 보여주는 view
def vote_result(request, question_id):
    question = Question.objects.get(pk=question_id)
    
    return render(request, 'poll/vote_result.html', {"question" : question})

16.Django/my_polls/poll/templates/poll/error_page.html
{% extends "layout.html" %}
{% block title%}Error page{% endblock title%}
{% block contents %} <h1>요청하신 작업을 처리하지 못했습니다.</h1>
이유 : {{error_message}}

{% endblock contents %}

16.Django/my_polls/poll/templates/poll/error_page_1st.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error page</title>
</head>
<body>
    <h1>요청하신 작업을 처리하지 못했습니다.</h1>
    이유 : {{error_message}}
    <p>
        <a href= "{% url 'poll:list' %}">설문 목록 페이지로 돌아가기</a>
    </p>
</body>
</html>

16.Django/my_polls/poll/templates/poll/list.html
{% extends "layout.html" %}
{% block title %}설문 목록{% endblock title%}
{% block contents %}    
<h1>설문 목록</h1>
설문 개수 : {{question_list|length}}
<ul>
    {% for question in question_list %}
        <li>
            <a href = "{% url 'poll:vote_form' question.pk %}">
                {{question.pk}}. {{question.question_text}}
            </a>
        </li>
    {% empty %}
        등록된 설문이 없습니다
    {% endfor%}
</ul>
{% endblock contents %}

16.Django/my_polls/poll/templates/poll/list_copy.html
<!--   Template   -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>설문 목록</title>
</head>
<body>
    <h1>설문 목록</h1>
    <!--view.py에 있는걸 뿌려야 하는데 거기서 바로 필요한게 html이 아닌 template-->
    <!--view에서 전달한 question_list값들을 출력 -->
    {# 장고 주석 #}
    {% comment %}
        장고주석1
        장고주석2
    {% endcomment %}
    {%comment%}
    {{question_list}} {# question_list의 변수값(View전달한 값)을 list로 출력 #}
    {%endcomment%}
    
    설문 개수 : {{question_list|length}}
    <ul>
        {% for question in question_list %}

            <li>
                <!--/poll/vote_form/question의 id-->
                <!--
                    <a href="/poll/vote_form/{{question.pk}}"> 
                    {{question.pk}}. {{question.question_text}}
                    </a>    -->
                {# url "app_name:path명" [path parameter에 넘길 값] #}
                <a href = "{% url 'poll:vote_form' question.pk %}">
                    {{question.pk}}. {{question.question_text}}
                </a>
                {{question.question_text}} ||
                {{question.question_text|truncatewords:1}} ||
                {{question.question_text|truncatechars:10}} ||
                {{question.pub_date}}||
                {{question.pub_date|date:'Y-m-d'}}
            </li>
        {% empty %}
            등록된 설문이 없습니다
        {% endfor%}
    </ul>
</body>
</html>

16.Django/my_polls/poll/templates/poll/vote_form copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote form</title>
    <script>
        function checkChoice(){
            //보기가 선택되지 않은 상태에서 전송했을 때, 전송되지 않도록 처리
            choiceList = document.vote_form.choice; //choice라디오 버튼을 조회(Node list 배열로 전환)
            cnt = 0;
            for (let i=0; i<choiceList.length; i++){
                if(choiceList[i].checked){
                    cnt++;
                    break;
                }
            }
            if(cnt==1){
                return true;
            }else{
                alert("응답을 선택해주세요")
                return false;
            }
        }
    </script>
</head>
<body>
    <h1>설문 양식</h1>
    <h2>{{question.pk}}. {{question.question_text}}</h2>
    {% if error_message != None %}
        <div style="color:rgb(185, 53, 53)">
            {{error_message}}
        </div>
    {% endif %}
    <form action="{% url 'poll:vote' %}" method="post" name="vote_form" onsubmit="return checkChoice()">
        {% csrf_token %} {#post 방식 요청시 반드시 넣어주어야 함. 보안관련 설정. csrf공격 방지를 위한 토큰값 생성#}

        <input type='hidden' name='question_id' value='{{question.pk}}'>

        {%for choice in question.choice_set.all%}
            <input type='radio' name='choice' value='{{choice.pk}}' id='{{choice.pk}}'>
            <label for='{{choice.pk}}'>{{choice.choice_text}}</label><br>
        {% empty %}
            등록된 보기가 없습니다.
        {% endfor %}
        <button type='submit'>투표</button>
        <button type='reset'>초기화</button>
    </form>
    
</body>
</html>

16.Django/my_polls/poll/templates/poll/vote_form.html
{% extends "layout.html"%}
{% block title %}Vote form{% endblock title%}
{% block script %} 
<script>
    function checkChoice(){
        //보기가 선택되지 않은 상태에서 전송했을 때, 전송되지 않도록 처리
        choiceList = document.vote_form.choice; //choice라디오 버튼을 조회(Node list 배열로 전환)
        cnt = 0;
        for (let i=0; i<choiceList.length; i++){
            if(choiceList[i].checked){
                cnt++;
                break;
            }
        }
        if(cnt==1){
            return true;
        }else{
            alert("응답을 선택해주세요")
            return false;
        }
    }
</script>
{% endblock script%}

{% block contents %}
<h1>설문 양식</h1>
<h2>{{question.pk}}. {{question.question_text}}</h2>
{% if error_message != None %}
    <div style="color:rgb(185, 53, 53)">
        {{error_message}}
    </div>
{% endif %}
<form action="{% url 'poll:vote' %}" method="post" name="vote_form" onsubmit="return checkChoice()">
    {% csrf_token %} {#post 방식 요청시 반드시 넣어주어야 함. 보안관련 설정. csrf공격 방지를 위한 토큰값 생성#}

    <input type='hidden' name='question_id' value='{{question.pk}}'>

    {%for choice in question.choice_set.all%}
        <input type='radio' name='choice' value='{{choice.pk}}' id='{{choice.pk}}'>
        <label for='{{choice.pk}}'>{{choice.choice_text}}</label><br>
    {% empty %}
        등록된 보기가 없습니다.
    {% endfor %}
    <button type='submit'>투표</button>
    <button type='reset'>초기화</button>
</form>
{% endblock contents %}


16.Django/my_polls/poll/templates/poll/vote_result.html
{% extends "layout.html" %}
{% block title %}Vote result{% endblock title%}
{% block contents %}
<h1>투표 결과</h1>
<h2>{{question.pk}}. {{question.question_text}}</h2>
<table width='150'>
    {% for choice in question.choice_set.all %}
    <tr>
        <td>{{choice.choice_text}}</td>
        <td>{{choice.vote}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock contents%}

16.Django/my_polls/templates/home.html
<!-- 시작 페이지 : layout.html을 상속 받아 만듦-->
{% extends "layout.html" %}

{% block title%}Home{% endblock title%}
{% block contents %}
    <h2>시작페이지</h2>
    안녕하세요. 설문 페이지에 오신 것을 환영합니다.
{% endblock contents%}

16.Django/my_polls/templates/layout.html
<!--
    layout 역할을 할 template
    - 모든 template에 공통적으로 들어갈 내용 작성
    - 각각의 template들이 자신의 코드들을 넣을 위치를 block 태그를 이용해 지정    
#}
--> 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}제목{% endblock title %}</title>
    {% block script %}{% endblock script%}
</head>
<body>
    <a href="{% url 'poll:list' %}">설문 리스트</a>
    <a href="/admin">관리자 페이지</a>
    <hr>
    {% block contents %}{% endblock contents %}
</body>
</html>